<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <StartupObject>GitHabInstaller.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Windows.Forms" Version="4.7.0" />
  </ItemGroup>

</Project>
